[pytest]
asyncio_mode = strict
asyncio_default_fixture_loop_scope = function
filterwarnings =
    ignore:Please use `import python_multipart` instead\.:PendingDeprecationWarning:starlette\.formparsers
    ignore:Type google\._upb\._message\.MessageMapContainer uses PyType_Spec with a metaclass that has custom tp_new\.:DeprecationWarning
    ignore:Type google\._upb\._message\.ScalarMapContainer uses PyType_Spec with a metaclass that has custom tp_new\.:DeprecationWarning
    ignore:ast\.NameConstant is deprecated and will be removed in Python 3\.14; use ast\.Constant instead:DeprecationWarning:reportlab\.lib\.rl_safe_eval
    ignore:The `update_forward_refs` method is deprecated; use `model_rebuild` instead\.:pydantic.warnings.PydanticDeprecatedSince20:gotrue\.types
