# Splunk Sentinel - Source Type Properties

[sentinel:investigation]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
NO_BINARY_CHECK = true
CHARSET = UTF-8
MAX_TIMESTAMP_LOOKAHEAD = 32
TIME_PREFIX = timestamp=
TIME_FORMAT = %Y-%m-%dT%H:%M:%S
TRANSFORMS-investigation = sentinel_investigation_fields

[sentinel:action]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
NO_BINARY_CHECK = true
CHARSET = UTF-8
MAX_TIMESTAMP_LOOKAHEAD = 32
TIME_PREFIX = executed_at=
TIME_FORMAT = %Y-%m-%dT%H:%M:%S
